// errors/ErrorCodes.js
const ErrorCodes = Object.freeze({
  // Application
  APPLICATION_NOT_READY: "APPLICATION_NOT_READY",

  // Browser
  BROWSER_NOT_READY: "BROWSER_NOT_READY",
  BROWSER_INITIALIZATION_FAILED: "BROWSER_INITIALIZATION_FAILED",
  BROWSER_OPERATION_FAILED: "BROWSER_OPERATION_FAILED",
  BROWSER_TAB_NOT_FOUND: "BROWSER_TAB_NOT_FOUND",
  BROWSER_NO_ACTIVE_TAB: "BROWSER_NO_ACTIVE_TAB",

  // Navigation
  INVALID_URL: "INVALID_URL",
  UNSUPPORTED_PROTOCOL: "UNSUPPORTED_PROTOCOL",
  NAVIGATION_FAILED: "NAVIGATION_FAILED",

  // IPC
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED_REQUEST: "UNAUTHORIZED_REQUEST",
  UNKNOWN_OPERATION: "UNKNOWN_OPERATION",

  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  MANAGER_DESTROYED: "MANAGER_DESTROYED",
  SURFACE_INVALID: "SURFACE_INVALID",
  SURFACE_ALREADY_REGISTERED: "SURFACE_ALREADY_REGISTERED",
  VIEW_UNAVAILABLE: "VIEW_UNAVAILABLE",
  SURFACE_NOT_FOUND: "SURFACE_NOT_FOUND",
  SURFACE_TEARDOWN_FAILED: "SURFACE_TEARDOWN_FAILED",
  WINDOW_UNAVAILABLE: "WINDOW_UNAVAILABLE",
  WINDOW_ALREADY_EXISTS: "WINDOW_ALREADY_EXISTS",
  WINDOW_CREATION_FAILED: "WINDOW_CREATION_FAILED",
  WINDOW_OPERATION_FAILED: "WINDOW_OPERATION_FAILED",
  CONTENT_VIEW_UNAVAILABLE: "CONTENT_VIEW_UNAVAILABLE",
  TAB_UNAVAILABLE: "TAB_UNAVAILABLE",
  TAB_ALREADY_ATTACHED: "TAB_ALREADY_ATTACHED",
  TAB_NOT_ATTACHED: "TAB_NOT_ATTACHED",
  SURFACE_ALREADY_ATTACHED: "SURFACE_ALREADY_ATTACHED",
  SURFACE_NOT_ATTACHED: "SURFACE_NOT_ATTACHED",
  SURFACE_ATTACHMENT_FAILED: "SURFACE_ATTACHMENT_FAILED",
  SURFACE_DETACHMENT_FAILED: "SURFACE_DETACHMENT_FAILED",
  SURFACE_BRING_TO_FRONT_FAILED: "SURFACE_BRING_TO_FRONT_FAILED",
  SURFACE_DESTROYED: "SURFACE_DESTROYED",
});

module.exports = ErrorCodes;
