module.exports = Object.freeze({
  INVALID_ARGUMENT: "INVALID_ARGUMENT",

  APPLICATION_NOT_READY: "APPLICATION_NOT_READY",
  APPLICATION_START_FAILED: "APPLICATION_START_FAILED",

  BROWSER_NOT_READY: "BROWSER_NOT_READY",
  BROWSER_INITIALIZATION_FAILED: "BROWSER_INITIALIZATION_FAILED",
  BROWSER_OPERATION_FAILED: "BROWSER_OPERATION_FAILED",
  BROWSER_NO_ACTIVE_TAB: "BROWSER_NO_ACTIVE_TAB",
  BROWSER_TAB_NOT_FOUND: "BROWSER_TAB_NOT_FOUND",
  BROWSER_TAB_DESTROYED: "BROWSER_TAB_DESTROYED",

  NAVIGATION_FAILED: "NAVIGATION_FAILED",

  IPC_NOT_READY: "IPC_NOT_READY",
  IPC_INVALID_REQUEST: "IPC_INVALID_REQUEST",
  IPC_HANDLER_FAILED: "IPC_HANDLER_FAILED",
  IPC_UNAUTHORIZED: "IPC_UNAUTHORIZED",

  PRESENTATION_INVALID_MODE: "PRESENTATION_INVALID_MODE",

  SURFACE_INVALID: "SURFACE_INVALID",
  SURFACE_ALREADY_REGISTERED: "SURFACE_ALREADY_REGISTERED",
  SURFACE_NOT_FOUND: "SURFACE_NOT_FOUND",
  SURFACE_NOT_MOUNTED: "SURFACE_NOT_MOUNTED",
  SURFACE_ATTACH_FAILED: "SURFACE_ATTACH_FAILED",
  SURFACE_DETACH_FAILED: "SURFACE_DETACH_FAILED",
  SURFACE_DESTROY_FAILED: "SURFACE_DESTROY_FAILED",
});
