const ErrorCodes = Object.freeze({
  // Application
  APPLICATION_NOT_READY: "APPLICATION_NOT_READY",

  // Browser
  BROWSER_NOT_READY: "BROWSER_NOT_READY",
  BROWSER_INITIALIZATION_FAILED: "BROWSER_INITIALIZATION_FAILED",
  BROWSER_OPERATION_FAILED: "BROWSER_OPERATION_FAILED",

  // Navigation
  INVALID_URL: "INVALID_URL",
  UNSUPPORTED_PROTOCOL: "UNSUPPORTED_PROTOCOL",
  NAVIGATION_FAILED: "NAVIGATION_FAILED",

  // IPC
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED_REQUEST: "UNAUTHORIZED_REQUEST",
  UNKNOWN_OPERATION: "UNKNOWN_OPERATION",

  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

module.exports = ErrorCodes;
